# Generated by Django 4.2.6 on 2023-12-09 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0002_userprofile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='address',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='bio',
            new_name='location',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='block',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='following',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='price',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
