# Generated by Django 4.2.6 on 2023-12-09 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0003_rename_address_userprofile_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraps',
            name='picture',
        ),
        migrations.RemoveField(
            model_name='scraps',
            name='user',
        ),
        migrations.AlterField(
            model_name='scraps',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
