# Generated by Django 4.2.6 on 2023-12-19 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0005_scraps_phone_no_scraps_picture_alter_scraps_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraps',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
