# Generated by Django 4.2.6 on 2024-01-20 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0007_cartlist_cartitems'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='scraps',
            name='priority',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='cartitems',
        ),
        migrations.DeleteModel(
            name='cartlist',
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
