# Generated by Django 4.2.6 on 2024-01-22 14:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap', '0011_product_remove_cartitem_owner_delete_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='scrap.userprofile')),
                ('products', models.ManyToManyField(related_name='CartItem', to='scrap.scraps')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='added_carts', to='scrap.order')),
            ],
        ),
        migrations.DeleteModel(
            name='cartitem',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
